nginx:
  replicaCount: 1
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: latest
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
